name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8 autoflake

    - name: Clean up unused imports and variables with autoflake
      run: |
        # Find all Python files and lint them
        find . -name "*.py" -exec autopep8 --in-place {} +
        echo "Cleaned all the Python files successfully"
        
    - name: Format with autopep
      run: |
        # Find all Python files and lint them
        find . -name "*.py" -exec autoflake --remove-all-unused-imports --remove-unused-variables --in-place {} +
        echo "Formatted all the Python files successfully"

    - name: Run Linter
      run: |
        # Find all Python files and lint them
        find . -name "*.py" -exec flake8 --max-line-length 160 {} +
        echo "Linted all the Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        # Install eslint locally in the project with all the plugins
        npm install eslint eslint-plugin-import eslint-plugin-react --save-dev
        #Install Prettier to format the files
        npm install prettier eslint-config-prettier eslint-plugin-prettier --save-dev
        
    - name: Run Linter
      run: |
          # Run eslint on all .js files, using the .eslintrc.json config file
          find . -name "node_modules" -prune -o -name "*.{jsx,js}" -exec npx eslint --fix {} +
          echo "Linted all the JavaScript files successfully"
